In [1]:
import numpy as np

In [10]:
arr=[[[1,2,3,4],[4,6,7,3],[4,7,2,9]]]
print(arr)
type(arr)

[[[1, 2, 3, 4], [4, 6, 7, 3], [4, 7, 2, 9]]]


list

In [11]:
a=np.array(arr)
print(a)
type(a)

[[[1 2 3 4]
  [4 6 7 3]
  [4 7 2 9]]]


numpy.ndarray

In [17]:
#dim(rank) of an array
a.ndim

3

In [133]:
#shape ( returns no of elements in each dimension) of an array
a.shape

(1, 3, 4)

In [132]:
#size ( returns no of elements) of an array
a.size

12

In [21]:
#dtype (returns type of elements in array) of an array
a.dtype

dtype('int32')

In [36]:
a.data

In [34]:
#np.zeros((3,3)) returns the array of dim 3
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
#np.ones((3,3)) returns the unit array of dim 3  
c=np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
#np.eye(4) returns 4x4 unit diagonal array
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#np.full((3,4),2) returns 3x4 array with all values 2
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [33]:
#np.random.rand(3,4) returns 3x4 array of random floats b/w 0-1
np.random.rand(3,4)

array([[0.24044251, 0.79836463, 0.86028742, 0.69041893],
       [0.94264353, 0.25333907, 0.57432964, 0.53968899],
       [0.53643314, 0.07225289, 0.37380353, 0.08097393]])

In [38]:
#operations


In [39]:
#copying

In [40]:
d=np.copy(a)
print(d)

[[[1 2 3 4]
  [4 6 7 3]
  [4 7 2 9]]]


In [ ]:
#Sorting

In [44]:
d.sort()  #sort array
print(d)

[[[1 2 3 4]
  [3 4 6 7]
  [2 4 7 9]]]


In [131]:
d.sort(axis=0) #row-wise sorting
print(d)

[[[2 2 2 2]
  [2 4 6 7]
  [3 4 7 9]]]


In [46]:
d.sort(axis=1) #column-wise sorting
print(d)

[[[1 2 3 4]
  [2 4 6 7]
  [3 4 7 9]]]


In [60]:
#Removing

In [65]:
np.delete(d,2,axis=1)

array([[[1, 2, 3, 4],
        [2, 4, 6, 7]]])

In [74]:
#combining
np.concatenate((d,a),axis=0)

array([[[1, 2, 3, 4],
        [2, 4, 6, 7],
        [3, 4, 7, 9]],

       [[1, 2, 3, 4],
        [4, 6, 7, 3],
        [4, 7, 2, 9]]])

In [80]:
e=np.concatenate((d,a),axis=1)
print(e)

[[[1 2 3 4]
  [2 4 6 7]
  [3 4 7 9]
  [1 2 3 4]
  [4 6 7 3]
  [4 7 2 9]]]


In [76]:
#Spliting

In [83]:
np.split(e,1)

[array([[[1, 2, 3, 4],
         [2, 4, 6, 7],
         [3, 4, 7, 9],
         [1, 2, 3, 4],
         [4, 6, 7, 3],
         [4, 7, 2, 9]]])]

In [84]:
#Indexing

In [87]:
a[0]=5
print(a)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [91]:
d[0,0]=2
print(d)

[[[2 2 2 2]
  [2 4 6 7]
  [3 4 7 9]]]


In [99]:
a[0,0]

array([5, 5, 5, 5])

## 

In [106]:
np.add(a,d)

array([[[ 7,  7,  7,  7],
        [ 7,  9, 11, 12],
        [ 8,  9, 12, 14]]])

In [108]:
np.subtract(a,d)

array([[[ 3,  3,  3,  3],
        [ 3,  1, -1, -2],
        [ 2,  1, -2, -4]]])

In [109]:
np.multiply(a,d)

array([[[10, 10, 10, 10],
        [10, 20, 30, 35],
        [15, 20, 35, 45]]])

In [110]:
np.divide(a,d)

array([[[2.5       , 2.5       , 2.5       , 2.5       ],
        [2.5       , 1.25      , 0.83333333, 0.71428571],
        [1.66666667, 1.25      , 0.71428571, 0.55555556]]])

In [111]:
np.exp(a)

array([[[148.4131591, 148.4131591, 148.4131591, 148.4131591],
        [148.4131591, 148.4131591, 148.4131591, 148.4131591],
        [148.4131591, 148.4131591, 148.4131591, 148.4131591]]])

In [112]:
np.sqrt(a)

array([[[2.23606798, 2.23606798, 2.23606798, 2.23606798],
        [2.23606798, 2.23606798, 2.23606798, 2.23606798],
        [2.23606798, 2.23606798, 2.23606798, 2.23606798]]])

In [117]:
f=([1,2,3,4],[0,7,5,4])
print(f)

([1, 2, 3, 4], [0, 7, 5, 4])


In [118]:
g=np.array(f)
print(g)

[[1 2 3 4]
 [0 7 5 4]]


In [119]:
g.sum()

26

In [120]:
g.min()

0

In [121]:
g.max()

7

In [125]:
g.max(axis=0)

array([1, 7, 5, 4])

In [134]:
g.max(axis=0)

array([1, 7, 5, 4])

In [135]:
g.mean()

3.25