In [1]:
import numpy as np

In [7]:
a=np.array([[[1,2,3],[8,1,5],[9,0,1]]])
b=np.array([[[8,4,2],[7,1,5],[7,8,3]]])
print(a)
print(b)

[[[1 2 3]
  [8 1 5]
  [9 0 1]]]
[[[8 4 2]
  [7 1 5]
  [7 8 3]]]


In [ ]:
#comparison

In [16]:
a==b #element-wise

array([[[False, False, False],
        [False, False,  True],
        [False, False,  True]]])

In [19]:
np.array_equal(a,b) #array-wise

False

In [18]:
#slicing

In [20]:
a[:]

array([[[1, 0, 1],
        [8, 1, 3],
        [9, 2, 5]]])

In [28]:
a[:,1]

array([[8, 1, 3]])

In [30]:
a[0:2,2]

array([[9, 2, 5]])

In [37]:
c=np.hstack((a,b))
c

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [7, 1, 2],
        [7, 4, 3],
        [8, 8, 5]]])

In [38]:
d=np.vstack((a,b))
d

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[7, 1, 2],
        [7, 4, 3],
        [8, 8, 5]]])

In [39]:
e=np.arange(2,11)  #(start,stop)
e

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
f=np.arange(13,131,13) #(start,stop,step)
f

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [60]:
arr=np.array([1,2,3])
print(arr)
arr +=5
arr

[1 2 3]


array([6, 7, 8])

In [61]:
g=np.random.randint(0,10,size=(3,2))
g

array([[0, 9],
       [5, 1],
       [1, 2]])

In [62]:
g.min()

0

In [63]:
g.max()

9

In [65]:
g.reshape(6,1)

array([[0],
       [9],
       [5],
       [1],
       [1],
       [2]])

In [69]:
h=np.array([[1,2,3],[8,1,5]])
h

array([[1, 2, 3],
       [8, 1, 5]])

In [70]:
y=h.T  #Transform
y

array([[1, 8],
       [2, 1],
       [3, 5]])